SASM	= SerenityASM.exe
SLINK	= SerenityLINK.exe
MV = copy
RM = del

SerenityOS.bit: bin\IntEntry.bit bin\IVT.bit bin\TVT.bit \
	bin\editor.bit bin\clear.bit bin\KBInt.bit bin\getchar.bit

	$(SLINK) -o SerenityOS.bit \
		bin\IntEntry.bit \
		bin\IVT.bit \
		bin\TVT.bit \
		bin\editor.bit bin\getchar.bit \
		bin\clear.bit bin\KBInt.bit

bin\\%.bit: src\%.mips
	$(SASM)	$<
	$(MV)	src\*.bit bin\*.bit
	$(RM)	src\*.bit
	
.PHONY: clean
clean:
	$(RM) bin\*.bit *.bit